<?php

declare (strict_types=1);
namespace Laminas\Service_Manager\Tool;

use function array_filter;
use function array_key_exists;
use function array_keys;
use function class_exists;
use function date;
use function gettype;
use function implode;
use function is_array;
use function is_int;
use function is_iterable;
use function is_string;
use Laminas\Service_Manager\Abstract_Factory\Config_Abstract_Factory;
use Laminas\Service_Manager\Exception\InvalidArgumentException;
use Psr\Container\Container_Interface;
use ReflectionClass;
use ReflectionNamedType;
use ReflectionParameter;
use function sprintf;
use function str_repeat;
use function var_export;
/**
 * @internal
 */
final readonly class Config_Dumper implements Config_Dumper_Interface
{
    public const CONFIG_TEMPLATE = <<<EOC
    <?php
    
    /**
     * This file generated by %s.
     * Generated %s
     */
    
    return %s;
    EOC;
    public const LAMINAS_MVC_SERVICEMANAGER_CONFIGURATION = 'service_manager';
    public const MEZZIO_CONTAINER_CONFIGURATION = 'dependencies';
    public function __construct(private ?Container_Interface $container = null, private string $service_manager_configuration_key = self::LAMINAS_MVC_SERVICEMANAGER_CONFIGURATION)
    {
    }
    public function create_dependency_config(array $config, string $class_name, bool $ignore_unresolved = false): array
    {
        $reflection_class = new ReflectionClass($class_name);
        $constructor = $reflection_class->get_constructor();
        // class has no constructor, treat it as an invokable
        if ($constructor === null) {
            return $this->create_invokable($config, $class_name);
        }
        // has no required parameters, treat it as an invokable
        if ($constructor->get_number_of_required_parameters() === 0) {
            return $this->create_invokable($config, $class_name);
        }
        $constructor_arguments = array_filter($constructor->get_parameters(), static fn(ReflectionParameter $argument): bool => !$argument->is_optional());
        $class_config = [];
        foreach ($constructor_arguments as $constructor_argument) {
            $type = $constructor_argument->get_type();
            $argument_type = $type instanceof ReflectionNamedType && !$type->is_builtin() ? $type->get_name() : null;
            if ($argument_type === null) {
                if ($ignore_unresolved) {
                    // don't throw an exception, just return the previous config
                    return $config;
                }
                // don't throw an exception if the class is an already defined service
                if ($this->container && $this->container->has($class_name)) {
                    return $config;
                }
                throw new InvalidArgumentException(sprintf('Cannot create config for constructor argument "%s", ' . 'it has no type hint, or non-class/interface type hint', $constructor_argument->get_name()));
            }
            $class_config[] = $argument_type;
            if (!class_exists($argument_type)) {
                continue;
            }
            $config = $this->create_dependency_config($config, $argument_type, $ignore_unresolved);
        }
        $config[Config_Abstract_Factory::class][$class_name] = $class_config;
        return $config;
    }
    /**
     * @param array<string,mixed>  $config
     * @param class-string $className
     * @return array<string,mixed>
     */
    private function create_invokable(array $config, string $class_name): array
    {
        $config[Config_Abstract_Factory::class][$class_name] = [];
        return $config;
    }
    public function create_factory_mappings_from_config(array $config): array
    {
        if (!array_key_exists(Config_Abstract_Factory::class, $config)) {
            return $config;
        }
        if (!is_array($config[Config_Abstract_Factory::class])) {
            throw new InvalidArgumentException('Config key for ' . Config_Abstract_Factory::class . ' should be an array, ' . gettype($config[Config_Abstract_Factory::class]) . ' given');
        }
        foreach (array_keys($config[Config_Abstract_Factory::class]) as $class_name) {
            $config = $this->create_factory_mappings($config, $class_name);
        }
        return $config;
    }
    public function create_factory_mappings(array $config, string $class_name): array
    {
        if (array_key_exists($this->service_manager_configuration_key, $config) && array_key_exists('factories', $config['service_manager']) && array_key_exists($class_name, $config['service_manager']['factories'])) {
            return $config;
        }
        $config['service_manager']['factories'][$class_name] = Config_Abstract_Factory::class;
        return $config;
    }
    public function dump_config_file(array $config): string
    {
        $prepared = $this->prepare_config($config);
        return sprintf(self::CONFIG_TEMPLATE, self::class, date('Y-m-d H:i:s'), $prepared);
    }
    /**
     * @param int<0,max> $indentLevel
     * @return non-empty-string
     */
    private function prepare_config(iterable $config, int $indent_level = 1): string
    {
        $indent = str_repeat(' ', $indent_level * 4);
        $entries = [];
        foreach ($config as $key => $value) {
            $key = $this->create_config_key($key);
            $entries[] = sprintf('%s%s%s,', $indent, $key !== null ? sprintf('%s => ', $key) : '', $this->create_config_value($value, $indent_level));
        }
        $outer_indent = str_repeat(' ', ($indent_level - 1) * 4);
        return sprintf("[\n%s\n%s]", implode("\n", $entries), $outer_indent);
    }
    /**
     * @return non-empty-string|null
     */
    private function create_config_key(string|int|null $key): string|null
    {
        if (is_string($key) && class_exists($key)) {
            return sprintf('\%s::class', $key);
        }
        if (is_int($key)) {
            return null;
        }
        return sprintf("'%s'", $key);
    }
    /**
     * @param int<0,max> $indentLevel
     */
    private function create_config_value(mixed $value, int $indent_level): string
    {
        if (is_iterable($value)) {
            return $this->prepare_config($value, $indent_level + 1);
        }
        if (is_string($value) && class_exists($value)) {
            return sprintf('\%s::class', $value);
        }
        return var_export($value, true);
    }
}